# Generated by Django 3.1.7 on 2021-11-20 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20211117_0455'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='featured_image',
            field=models.ImageField(blank=True, default='images/profile_pics/default.jpg', null=True, upload_to=''),
        ),
    ]
